import { MetadataRoute } from 'next'

export default function robots(): MetadataRoute.Robots {
  const baseUrl = process.env.NEXT_PUBLIC_URL || 'http://localhost:3000'

  return {
    rules: [
      {
        userAgent: '*',
        allow: [
          '/',
          '/pricing',
          '/contact',
          '/story',
          '/features',
          '/features/',
          '/resources',
          '/resources/',
          '/site-map',
          '/site-map/',
          '/docs',
          '/docs/',
          '/integrations',
          '/integrations/',
          '/privacy',
          '/terms',
          '/terms-and-conditions',
        ],
        disallow: [
          '/admin',
          '/admin/',
          '/apps',
          '/apps/',
          '/overview',
          '/overview/',
          '/clients',
          '/clients/',
          '/expenses',
          '/expenses/',
          '/inbox',
          '/inbox/',
          '/invoices',
          '/invoices/',
          '/notifications',
          '/notifications/',
          '/products',
          '/products/',
          '/recurring',
          '/recurring/',
          '/transactions',
          '/transactions/',
          '/upgrade',
          '/upgrade/',
          '/settings',
          '/settings/',
          '/api',
          '/api/',
          '/auth',
          '/auth/',
          '/invite',
          '/invite/',
          '/pay',
          '/pay/',
          '/view',
          '/view/',
          '/login',
        ],
      },
    ],
    sitemap: `${baseUrl}/sitemap.xml`,
  }
}
