import { MetadataRoute } from 'next'

export default function robots(): MetadataRoute.Robots {
  const baseUrl =
    process.env.NEXT_PUBLIC_URL ||
    process.env.NEXT_PUBLIC_SITE_URL ||
    'https://www.illumi.co.za'

  return {
    rules: [
      {
        userAgent: '*',
        allow: [
          '/',
          '/pricing',
          '/contact',
          '/story',
          '/features',
          '/features/',
          '/features/*',
          '/blog',
          '/blog/',
          '/blog/*',
          '/resources',
          '/resources/',
          '/resources/*',
          '/docs',
          '/docs/',
          '/docs/*',
          '/integrations',
          '/integrations/',
          '/integrations/*',
          '/glossary',
          '/glossary/',
          '/glossary/*',
          '/compare',
          '/compare/',
          '/compare/*',
          '/help',
          '/help/',
          '/help/*',
          '/what-is-an-invoice',
          '/invoice-generator',
          '/invoice-software-south-africa',
          '/billing-invoicing-software',
          '/online-invoicing',
          '/invoice-management-system',
          '/invoicing-software',
          '/invoicing-software/*',
          '/hourly-rate-calculator',
          '/percentage-calculator',
          '/sales-tax-calculator',
          '/for-business',
          '/for-individuals',
          '/mobile-app',
          '/receipt-maker',
          '/invoice-template',
          '/invoice-creator',
          '/invoice-maker',
          '/free-invoice-generator',
          '/proforma-invoice-template',
          '/freelance-invoice-template',
          '/landing-page',
          '/try',
          '/privacy',
          '/terms',
          '/terms-and-conditions',
        ],
        disallow: [
          '/apps',
          '/apps/',
          '/overview',
          '/overview/',
          '/clients',
          '/clients/',
          '/expenses',
          '/expenses/',
          '/inbox',
          '/inbox/',
          '/invoices',
          '/invoices/',
          '/notifications',
          '/notifications/',
          '/products',
          '/products/',
          '/vault',
          '/vault/',
          '/recurring',
          '/recurring/',
          '/transactions',
          '/transactions/',
          '/upgrade',
          '/upgrade/',
          '/settings',
          '/settings/',
          '/api',
          '/api/',
          '/auth',
          '/auth/',
          '/invite',
          '/invite/',
          '/pay',
          '/pay/',
          '/view',
          '/view/',
          '/login',
        ],
      },
    ],
    sitemap: `${baseUrl}/sitemap.xml`,
  }
}
